name: auto-open-pr
on:
  push:
    branches:
      - deploy
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4
      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "murali@banyancloud.io"
          git config --global user.name "bds1959"
      # Commit changes
      - name: pull branch
        run: git pull
      # Open PR
      - name: Create Pull Request
        id: npm-publish
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: npm publish - open PR - added tag
          title: npm publish - open PR
          body: npm publish - open PR
          base: master
          labels: automated-pr, npm publish
          branch: deploy
#           delete-branch: true
      # auto approve PR
      - name: Auto approve
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GMKR }}
          number: ${{ steps.npm-publish.outputs.pull-request-number }}
      # auto merge PR
      - name: Auto merge PR
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GMKR }}
          number: ${{ steps.npm-publish.outputs.pull-request-number }}
          method: squash

